@startuml

title Securing internal services on Google Cloud Platform with external Auth service

' scale 1000 width

!$disabled_arrow = "#lightgray"
!$enabled_arrow = "thickness=2"

!$disabled = "<color:lightgray><size:14>"
!$enabled = "<size:14>"

rectangle "<size:20>Client" as Client #LightCyan
rectangle "AUTH" as Auth
rectangle "API_GATEWAY" as APIG

rectangle GCP #LightCyan {
    node "ServiceA" as ServiceA
    node "ServiceB" as ServiceB
    node "ServiceC" as ServiceC
    queue "Kafka" as Queue
}

' start
Client -right[$disabled_arrow]-> Auth : $disabled Get Token
Client -right[$disabled_arrow]-> APIG : $disabled Pass token
APIG -up[$disabled_arrow]-> Auth : $disabled Validate token
APIG -right[$disabled_arrow]-> ServiceA : $disabled Pass token
ServiceA -up[$disabled_arrow]-> Auth : $disabled Validate token
ServiceA -right[$disabled_arrow]-> ServiceB : $disabled Pass token
ServiceB -up[$disabled_arrow]-> Auth : $disabled Validate token
ServiceA -down[$disabled_arrow]-> Queue : $disabled Pass token
Queue -down[$disabled_arrow]-> ServiceC : $disabled Pass token
ServiceC -up[$disabled_arrow]-> Auth : $disabled Validate token
' end

@enduml
