@startuml

' scale 1000 width

!$disabled = "<color:lightgray><size:14>"

rectangle "<size:20>Client" as Client #LightCyan
rectangle "AUTH" as Auth
rectangle "API_GATEWAY" as APIG

rectangle GCP #LightCyan {
    node "ServiceA" as ServiceA
    node "ServiceB" as ServiceB
    node "ServiceC" as ServiceC
    queue "Kafka" as Queue
}

' start
Client -right[#lightgray]-> Auth : $disabled Get Token
Client -right[#lightgray]-> APIG : $disabled Pass token
APIG -up[#lightgray]-> Auth : $disabled Validate token
APIG -right[#lightgray]-> ServiceA : $disabled Pass token
ServiceA -up[#lightgray]-> Auth : $disabled Validate token
ServiceA -right[#lightgray]-> ServiceB : $disabled Pass token
ServiceB -up[#lightgray]-> Auth : $disabled Validate token
ServiceA -down[#lightgray]-> Queue : $disabled Pass token
Queue -down[#lightgray]-> ServiceC : $disabled Pass token
ServiceC -up[#lightgray]-> Auth : $disabled Validate token
' end

@enduml
